### ISSUE TITLE
installation dependency tree broken

### ISSUE THREAD

**Issue by Axl-Lvy** [pubnub/moderation-dashboard#17]
When I try to run `npm install` i get
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: material-ui-search-bar@1.0.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@"*" from @testing-library/react@11.2.6
npm ERR!   node_modules/@testing-library/react
npm ERR!     dev @testing-library/react@"^11.2.6" from the root project
npm ERR!   20 more (@wojtekmaj/enzyme-adapter-react-17, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from material-ui-search-bar@1.0.0
npm ERR! node_modules/material-ui-search-bar
npm ERR!   material-ui-search-bar@"^1.0.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@"^16.8.0" from material-ui-search-bar@1.0.0
npm ERR!   node_modules/material-ui-search-bar
npm ERR!     material-ui-search-bar@"^1.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
So I try `npm install --force`

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\Axel\IdeaProjects\moderation-dashboard\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\Axel\IdeaProjects\moderation-dashboard\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\Axel\IdeaProjects\moderation-dashboard\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\Axel\IdeaProjects\moderation-dashboard\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\Axel\IdeaProjects\moderation-dashboard\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\Axel\IdeaProjects\moderation-dashboard\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\Axel\IdeaProjects\moderation-dashboard\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\Axel\IdeaProjects\moderation-dashboard\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
    at C:\Users\Axel\IdeaProjects\moderation-dashboard\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\Axel\IdeaProjects\moderation-dashboard\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\Axel\IdeaProjects\moderation-dashboard\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\Axel\IdeaProjects\moderation-dashboard\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\Axel\IdeaProjects\moderation-dashboard\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```
I think the package versions required are way to old (for example uuid asked v3, which is currently on v7)

**Comment by SimbaNetropolix** [comment]
Noticed this issue as well, an upgrade is needed to all packages and especially Material UI as a lot of the styling HOC have been deprecated. I did this myself but the result was broken functionalities although I was able to run it.
